# Generated by Django 4.2 on 2023-04-08 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone_accounts_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truecaller', models.TextField()),
                ('phone_no', models.CharField(max_length=10)),
                ('base', models.TextField()),
                ('facebook', models.BooleanField()),
                ('google', models.TextField()),
                ('twitter', models.BooleanField()),
                ('instagram', models.BooleanField()),
                ('yahoo', models.BooleanField()),
                ('microsoft', models.BooleanField()),
                ('snapchat', models.BooleanField()),
                ('skype', models.TextField()),
                ('whatsapp', models.TextField()),
                ('telegram', models.TextField()),
                ('viber', models.TextField()),
                ('Kakao', models.BooleanField()),
                ('ok', models.BooleanField()),
                ('zalo', models.BooleanField()),
                ('line', models.BooleanField()),
                ('flipkart', models.BooleanField()),
                ('bukalapak', models.BooleanField()),
                ('jdid', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Email_accounts_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('base', models.TextField()),
                ('apple', models.BooleanField()),
                ('ebay', models.BooleanField()),
                ('facebook', models.BooleanField()),
                ('flickr', models.BooleanField()),
                ('four_square', models.BooleanField()),
                ('github', models.BooleanField()),
                ('google', models.TextField()),
                ('gravatar', models.TextField()),
                ('instagram', models.TextField()),
                ('telegram', models.BooleanField()),
                ('lastfm', models.BooleanField()),
                ('linkedin', models.TextField()),
                ('microsoft', models.BooleanField()),
                ('myspace', models.BooleanField()),
                ('pinterest', models.BooleanField()),
                ('skype', models.TextField()),
                ('spotify', models.BooleanField()),
                ('tumblr', models.BooleanField()),
                ('twitter', models.BooleanField()),
                ('vimeo', models.BooleanField()),
                ('weibo', models.BooleanField()),
                ('yahoo', models.BooleanField()),
                ('discord', models.BooleanField()),
                ('ok', models.TextField()),
                ('kakao', models.BooleanField()),
                ('booking', models.BooleanField()),
                ('airbnb', models.TextField()),
                ('amazon', models.BooleanField()),
                ('qzone', models.BooleanField()),
                ('adobe', models.BooleanField()),
                ('mailru', models.BooleanField()),
                ('wordpress', models.BooleanField()),
                ('imgur', models.BooleanField()),
                ('disneyplus', models.BooleanField()),
                ('netflix', models.BooleanField()),
                ('jdid', models.BooleanField()),
                ('flipkart', models.BooleanField()),
                ('bukalapak', models.BooleanField()),
                ('archiveorg', models.BooleanField()),
                ('lazda', models.BooleanField()),
                ('zoho', models.BooleanField()),
                ('samsung', models.BooleanField()),
                ('evernote', models.BooleanField()),
                ('envato', models.BooleanField()),
                ('patreon', models.BooleanField()),
                ('tokopedia', models.BooleanField()),
                ('rambler', models.BooleanField()),
                ('quora', models.BooleanField()),
                ('atlassian', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
