# Generated by Django 4.2 on 2023-04-09 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_email_accounts_details_flickr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_accounts_details',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='phone_accounts_details',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
